---
- name: Pull Docker Image from Docker Hub and Run Container
  hosts: localhost
  remote_user: maitri
  become: false
  tasks:

    - name: Install Python Docker SDK
      ansible.builtin.pip:
        name: docker
        extra_args: --break-system-packages
        executable: pip3

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker Image
      community.docker.docker_image:
        name: "mtrivedi1410/trialcalc"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Run Docker container
      community.docker.docker_container:
        name: calculator
        image: "mtrivedi1410/trialcalc"
        state: started
        interactive: yes
        tty: yes
        detach: yes
